import { Resident, Household, DemographicStat } from "@/types/inhabitants";

export const INITIAL_RESIDENTS: Resident[] = [
  {
    id: "RES-2026-0001",
    firstName: "Juan",
    lastName: "Dela Cruz",
    middleName: "Santos",
    gender: "Male",
    birthDate: "1960-04-12",
    age: 66,
    civilStatus: "Married",
    contactNumber: "0917-123-4567",
    email: "juan.delacruz@gmail.com",
    address: "15 Sta. Lucia Street, Brgy. Sta. Lucia, Quezon City",
    street: "Sta. Lucia St.",
    householdId: "HH-STL-0101",
    isHeadOfHousehold: true,
    relationshipToHead: "Head",
    voterStatus: "Registered",
    precinctNo: "0412-A",
    occupation: "Retired Educator",
    educationalAttainment: "College",
    isPwd: false,
    isSenior: true,
    isSoloParent: false,
    isIndigent: false,
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    status: "Active",
    emergencyContactName: "Maria Dela Cruz",
    emergencyContactPhone: "0918-234-5678",
    emergencyContactRelation: "Spouse",
    dateRegistered: "2024-01-15",
  },
  {
    id: "RES-2026-0002",
    firstName: "Maria",
    lastName: "Dela Cruz",
    middleName: "Reyes",
    gender: "Female",
    birthDate: "1963-09-24",
    age: 62,
    civilStatus: "Married",
    contactNumber: "0918-234-5678",
    email: "maria.delacruz@gmail.com",
    address: "15 Sta. Lucia Street, Brgy. Sta. Lucia, Quezon City",
    street: "Sta. Lucia St.",
    householdId: "HH-STL-0101",
    isHeadOfHousehold: false,
    relationshipToHead: "Spouse",
    voterStatus: "Registered",
    precinctNo: "0412-A",
    occupation: "Homemaker",
    educationalAttainment: "College",
    isPwd: false,
    isSenior: true,
    isSoloParent: false,
    isIndigent: false,
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    status: "Active",
    emergencyContactName: "Juan Dela Cruz",
    emergencyContactPhone: "0917-123-4567",
    emergencyContactRelation: "Spouse",
    dateRegistered: "2024-01-15",
  },
  {
    id: "RES-2026-0003",
    firstName: "Mark Anthony",
    lastName: "Dela Cruz",
    middleName: "Reyes",
    gender: "Male",
    birthDate: "1992-11-05",
    age: 33,
    civilStatus: "Single",
    contactNumber: "0919-345-6789",
    email: "mark.delacruz@tech.ph",
    address: "15 Sta. Lucia Street, Brgy. Sta. Lucia, Quezon City",
    street: "Sta. Lucia St.",
    householdId: "HH-STL-0101",
    isHeadOfHousehold: false,
    relationshipToHead: "Son",
    voterStatus: "Registered",
    precinctNo: "0412-B",
    occupation: "Software Engineer",
    educationalAttainment: "College",
    isPwd: false,
    isSenior: false,
    isSoloParent: false,
    isIndigent: false,
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    status: "Active",
    emergencyContactName: "Juan Dela Cruz",
    emergencyContactPhone: "0917-123-4567",
    emergencyContactRelation: "Father",
    dateRegistered: "2024-02-10",
  },
  {
    id: "RES-2026-0004",
    firstName: "Elena",
    lastName: "Gonzales",
    middleName: "Bautista",
    gender: "Female",
    birthDate: "1984-03-18",
    age: 42,
    civilStatus: "Widowed",
    contactNumber: "0920-456-7890",
    email: "elena.gonzales@yahoo.com",
    address: "88 Maligaya Street, Brgy. Sta. Lucia, Quezon City",
    street: "Maligaya St.",
    householdId: "HH-STL-0102",
    isHeadOfHousehold: true,
    relationshipToHead: "Head",
    voterStatus: "Registered",
    precinctNo: "0415-A",
    occupation: "Sari-Sari Store Owner",
    educationalAttainment: "High School",
    isPwd: false,
    isSenior: false,
    isSoloParent: true,
    isIndigent: true,
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    status: "Active",
    emergencyContactName: "Teresa Gonzales",
    emergencyContactPhone: "0921-567-8901",
    emergencyContactRelation: "Sister",
    dateRegistered: "2024-03-01",
  },
  {
    id: "RES-2026-0005",
    firstName: "Joshua",
    lastName: "Gonzales",
    middleName: "Bautista",
    gender: "Male",
    birthDate: "2010-08-14",
    age: 16,
    civilStatus: "Single",
    contactNumber: "0921-987-6543",
    address: "88 Maligaya Street, Brgy. Sta. Lucia, Quezon City",
    street: "Maligaya St.",
    householdId: "HH-STL-0102",
    isHeadOfHousehold: false,
    relationshipToHead: "Son",
    voterStatus: "Non-Registered",
    occupation: "Student",
    educationalAttainment: "High School",
    isPwd: true,
    pwdType: "Mobility Impairment",
    isSenior: false,
    isSoloParent: false,
    isIndigent: true,
    avatarUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    status: "Active",
    emergencyContactName: "Elena Gonzales",
    emergencyContactPhone: "0920-456-7890",
    emergencyContactRelation: "Mother",
    dateRegistered: "2024-03-01",
  },
  {
    id: "RES-2026-0006",
    firstName: "Ramon",
    lastName: "Santos",
    middleName: "Villanueva",
    suffix: "Sr.",
    gender: "Male",
    birthDate: "1951-01-30",
    age: 75,
    civilStatus: "Married",
    contactNumber: "0922-678-9012",
    email: "ramon.santos@outlook.com",
    address: "42 Regalado Avenue, Brgy. Sta. Lucia, Quezon City",
    street: "Regalado Ave.",
    householdId: "HH-STL-0103",
    isHeadOfHousehold: true,
    relationshipToHead: "Head",
    voterStatus: "Registered",
    precinctNo: "0418-C",
    occupation: "Retired Civil Engineer",
    educationalAttainment: "College",
    isPwd: true,
    pwdType: "Visual Impairment",
    isSenior: true,
    isSoloParent: false,
    isIndigent: false,
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    status: "Active",
    emergencyContactName: "Corazon Santos",
    emergencyContactPhone: "0923-789-0123",
    emergencyContactRelation: "Spouse",
    dateRegistered: "2024-01-20",
  },
  {
    id: "RES-2026-0007",
    firstName: "Corazon",
    lastName: "Santos",
    middleName: "Mendoza",
    gender: "Female",
    birthDate: "1955-07-19",
    age: 71,
    civilStatus: "Married",
    contactNumber: "0923-789-0123",
    address: "42 Regalado Avenue, Brgy. Sta. Lucia, Quezon City",
    street: "Regalado Ave.",
    householdId: "HH-STL-0103",
    isHeadOfHousehold: false,
    relationshipToHead: "Spouse",
    voterStatus: "Registered",
    precinctNo: "0418-C",
    occupation: "Former Accountant",
    educationalAttainment: "College",
    isPwd: false,
    isSenior: true,
    isSoloParent: false,
    isIndigent: false,
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    status: "Active",
    emergencyContactName: "Ramon Santos",
    emergencyContactPhone: "0922-678-9012",
    emergencyContactRelation: "Spouse",
    dateRegistered: "2024-01-20",
  },
  {
    id: "RES-2026-0008",
    firstName: "Beatriz",
    lastName: "Aquino",
    middleName: "Cruz",
    gender: "Female",
    birthDate: "1998-05-14",
    age: 28,
    civilStatus: "Single",
    contactNumber: "0925-890-1234",
    email: "bea.aquino@designhouse.ph",
    address: "102 Lilac Street, Brgy. Sta. Lucia, Quezon City",
    street: "Lilac St.",
    householdId: "HH-STL-0104",
    isHeadOfHousehold: true,
    relationshipToHead: "Head",
    voterStatus: "Registered",
    precinctNo: "0420-A",
    occupation: "Graphic Designer",
    educationalAttainment: "College",
    isPwd: false,
    isSenior: false,
    isSoloParent: false,
    isIndigent: false,
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    status: "Active",
    emergencyContactName: "Carlos Aquino",
    emergencyContactPhone: "0926-901-2345",
    emergencyContactRelation: "Brother",
    dateRegistered: "2024-04-12",
  },
  {
    id: "RES-2026-0009",
    firstName: "Carlos",
    lastName: "Aquino",
    middleName: "Cruz",
    gender: "Male",
    birthDate: "2001-09-02",
    age: 24,
    civilStatus: "Single",
    contactNumber: "0926-901-2345",
    email: "carlos.aquino@student.upd.edu.ph",
    address: "102 Lilac Street, Brgy. Sta. Lucia, Quezon City",
    street: "Lilac St.",
    householdId: "HH-STL-0104",
    isHeadOfHousehold: false,
    relationshipToHead: "Brother",
    voterStatus: "Registered",
    precinctNo: "0420-A",
    occupation: "University Student",
    educationalAttainment: "College",
    isPwd: false,
    isSenior: false,
    isSoloParent: false,
    isIndigent: false,
    avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    status: "Active",
    emergencyContactName: "Beatriz Aquino",
    emergencyContactPhone: "0925-890-1234",
    emergencyContactRelation: "Sister",
    dateRegistered: "2024-04-12",
  },
  {
    id: "RES-2026-0010",
    firstName: "Pedro",
    lastName: "Mercado",
    middleName: "Ramos",
    gender: "Male",
    birthDate: "1978-12-03",
    age: 47,
    civilStatus: "Married",
    contactNumber: "0927-012-3456",
    address: "24 Katipunan Extension, Brgy. Sta. Lucia, Quezon City",
    street: "Katipunan Ext.",
    householdId: "HH-STL-0105",
    isHeadOfHousehold: true,
    relationshipToHead: "Head",
    voterStatus: "Registered",
    precinctNo: "0422-B",
    occupation: "Tricycle Driver",
    educationalAttainment: "High School",
    isPwd: false,
    isSenior: false,
    isSoloParent: false,
    isIndigent: true,
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    status: "Active",
    emergencyContactName: "Ana Mercado",
    emergencyContactPhone: "0928-123-4567",
    emergencyContactRelation: "Spouse",
    dateRegistered: "2024-02-18",
  }
];

export const INITIAL_HOUSEHOLDS: Household[] = [
  {
    id: "HH-STL-0101",
    householdNo: "HH-2026-0101",
    headName: "Juan Dela Cruz",
    headId: "RES-2026-0001",
    street: "Sta. Lucia St.",
    fullAddress: "15 Sta. Lucia Street, Brgy. Sta. Lucia, Quezon City",
    memberCount: 3,
    familyIncomeCategory: "Upper Middle",
    housingType: "Owned",
    members: INITIAL_RESIDENTS.filter((r) => r.householdId === "HH-STL-0101"),
  },
  {
    id: "HH-STL-0102",
    householdNo: "HH-2026-0102",
    headName: "Elena Gonzales",
    headId: "RES-2026-0004",
    street: "Maligaya St.",
    fullAddress: "88 Maligaya Street, Brgy. Sta. Lucia, Quezon City",
    memberCount: 2,
    familyIncomeCategory: "Low Income",
    housingType: "Rented",
    members: INITIAL_RESIDENTS.filter((r) => r.householdId === "HH-STL-0102"),
  },
  {
    id: "HH-STL-0103",
    householdNo: "HH-2026-0103",
    headName: "Ramon Santos Sr.",
    headId: "RES-2026-0006",
    street: "Regalado Ave.",
    fullAddress: "42 Regalado Avenue, Brgy. Sta. Lucia, Quezon City",
    memberCount: 2,
    familyIncomeCategory: "Middle",
    housingType: "Owned",
    members: INITIAL_RESIDENTS.filter((r) => r.householdId === "HH-STL-0103"),
  },
  {
    id: "HH-STL-0104",
    householdNo: "HH-2026-0104",
    headName: "Beatriz Aquino",
    headId: "RES-2026-0008",
    street: "Lilac St.",
    fullAddress: "102 Lilac Street, Brgy. Sta. Lucia, Quezon City",
    memberCount: 2,
    familyIncomeCategory: "Middle",
    housingType: "Rented",
    members: INITIAL_RESIDENTS.filter((r) => r.householdId === "HH-STL-0104"),
  },
  {
    id: "HH-STL-0105",
    householdNo: "HH-2026-0105",
    headName: "Pedro Mercado",
    headId: "RES-2026-0010",
    street: "Katipunan Ext.",
    fullAddress: "24 Katipunan Extension, Brgy. Sta. Lucia, Quezon City",
    memberCount: 1,
    familyIncomeCategory: "Low Income",
    housingType: "Informal Settler",
    members: INITIAL_RESIDENTS.filter((r) => r.householdId === "HH-STL-0105"),
  },
];

export const INITIAL_DEMOGRAPHICS: DemographicStat = {
  totalPopulation: 14820,
  totalHouseholds: 3410,
  totalSeniorCitizens: 1845,
  totalPwds: 492,
  totalSoloParents: 615,
  totalIndigents: 1120,
  totalRegisteredVoters: 9850,
  ageDistribution: [
    { category: "Children (0-12 yrs)", count: 2964, percentage: 20 },
    { category: "Youth (13-24 yrs)", count: 3705, percentage: 25 },
    { category: "Adults (25-59 yrs)", count: 6306, percentage: 42.5 },
    { category: "Seniors (60+ yrs)", count: 1845, percentage: 12.5 },
  ],
  genderRatio: {
    maleCount: 7260,
    femaleCount: 7560,
    malePercentage: 49,
    femalePercentage: 51,
  },
  employmentStats: [
    { category: "Employed (Private/Gov)", count: 5928, percentage: 40 },
    { category: "Self-Employed / Business", count: 2964, percentage: 20 },
    { category: "Students", count: 3260, percentage: 22 },
    { category: "Unemployed / Seeking", count: 1482, percentage: 10 },
    { category: "Retired", count: 1186, percentage: 8 },
  ],
  educationStats: [
    { category: "Elementary", count: 1778, percentage: 12 },
    { category: "High School", count: 5335, percentage: 36 },
    { category: "Vocational", count: 1482, percentage: 10 },
    { category: "College Degree", count: 5483, percentage: 37 },
    { category: "Post-Graduate", count: 742, percentage: 5 },
  ],
};
